export const DEPARTMENTS: Record<string, string[]> = {
  BE: [
    "Civil Engineering",
    "Urban Engineering",
    "Petroleum Engineering",
    "Mechanical Engineering",
    "Textile Engineering",
    "Industrial & Manufacturing Engineering",
    "Automotive Engineering",
    "Electrical Engineering",
    "Electronic Engineering",
    "Telecommunications Engineering",
    "Computer & Information Systems Engineering",
    "Materials Engineering",
    "Chemical Engineering",
    "Metallurgical Engineering",
    "Polymer & Petrochemical Engineering",
    "Food Engineering",
    "Bio-Medical Engineering",
  ],
  BS: [
    "Computer Science",
    "Software Engineering",
    "Artificial Intelligence",
    "Data Science",
    "Cyber Security",
    "Development Studies",
    "Economics & Finance",
    "English Linguistics",
    "Industrial Chemistry",
    "Applied Physics",
    "Applied Mathematics",
    "Computational Finance",
    "Textile Sciences",
    "Management Sciences",
    "Architecture",
  ],
};

export const SEMESTERS = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th"];
